version:'3.8'

services:
    
    web:
      container_name: resumecon
      build:
        context: .

      command: gunicorn --bind "0.0.0.0:8000" EmployeeSalary.wsgi:application

      ports:
        - "8001:8000"

    ngnix:
      container_name: nginx
      image: nginx:latest
      volumes:
         - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      
      ports:
         - "81:80"

      depends_on:
          - web